### PR TITLE
Avoid warning : variable "v" is used before its value is set

### PR DESCRIPTION
**Pull request by pramodk**

### CODE REVIEW

**Comment by pramodk** [comment]
All usages are safe : v is passed as argument but that was not used at the end:

```
#define _threadargscomma_ _iml, _cntml_padded, _p, _ppvar, _thread, _nt, v,

void _net_receive (Point_process* _pnt, int _weight_index, double _lflag)
{  double* _p; Datum* _ppvar; ThreadDatum* _thread; double v;
   Memb_list* _ml; int _cntml_padded, _cntml_actual; int _iml; double* _args;

   NrnThread* _nt;
   int _tid = _pnt->_tid;
   _nt = nrn_threads + _tid;
   _thread = (ThreadDatum*)0;
   double *_weights = _nt->_weights;
   _args = _weights + _weight_index;
   _ml = _nt->_ml_list[_pnt->_type];
   _cntml_actual = _ml->_nodecount;
   _cntml_padded = _ml->_nodecount_padded;
   _iml = _pnt->_i_instance;
#if LAYOUT == 1 /*AoS*/
   _p = _ml->_data + _iml*_psize; _ppvar = _ml->_pdata + _iml*_ppsize;
#endif
#if LAYOUT == 0 /*SoA*/
   _p = _ml->_data; _ppvar = _ml->_pdata;
#endif
#if LAYOUT > 1 /*AoSoA*/
#error AoSoA not implemented.
#endif
  #if !defined(_OPENACC)
 assert(_tsav <= t);
 #endif
 _tsav = t;
#if !NET_RECEIVE_BUFFERING
  if (_lflag == 1. ) {*(_tqitem) = 0;}
#endif
 {
   if ( _lflag  == 0.0 ) {
     if ( _args[0] > 0.0  && on  == 0.0 ) {
       init_sequence ( _threadargscomma_ t ) ;
       next_invl ( _threadargs_ ) ;
       event = event - interval * ( 1. - noise ) ;
       artcell_net_send ( _tqitem, _weight_index, _pnt, t +  event , 1.0 ) ;
       }
     else if ( _args[0] < 0.0 ) {
       on = 0.0 ;
       }
     }
   if ( _lflag  == 3.0 ) {
     if ( on  == 1.0 ) {
       init_sequence ( _threadargscomma_ t ) ;
       artcell_net_send ( _tqitem, _weight_index, _pnt, t +  0.0 , 1.0 ) ;
       }
     }
   if ( _lflag  == 1.0  && on  == 1.0 ) {
     ispike = ispike + 1.0 ;
     net_event ( _pnt, t ) ;
     next_invl ( _threadargs_ ) ;
     if ( on  == 1.0 ) {
       artcell_net_send ( _tqitem, _weight_index, _pnt, t +  event , 1.0 ) ;
       }
     }
   }
#if NET_RECEIVE_BUFFERING
#undef t
#define t _nt->_t
#endif
 }
```

**Comment by nrnhines** [comment]
> All usages are safe
I'm not so sure. ```init_sequence ( _threadargscomma_ t ) ;``` and ```next_invl ( _threadargs_ ) ;``` don't use v but another mod file might use v.  If I remember correctly, there is even special nocpout code that checks if v is used in the NET_RECEIVE block but that would be insufficient if a called function used v. I think I need to check this further. Note that in NEURON, nocmodl, _threadargs_ does not have v because it is part of the _p array. Ie. in expsyn.c,```#define v _p[5]```

**Comment by pramodk** [comment]
That’s true! If called function in NET_RECEIVE uses  v then that would be a problem !

There is condition check whether to initialise v from actual_v. I think we can always initialise v.

**Comment by nrnhines** [comment]
> There is condition check 

I didn't remember if I had done that for mod2c. (And still haven't looked) But if so
> I think we can always initialise v.

then go ahead and do that. It would probably be too tedious to check the entire call chain to be able to ```v = 0.0;``` instead of
always ```v = nt->_actual_v[_iml];```

**Comment by nrnhines** [comment]
Here is a test that demonstrates a similar bug in NEURON. If there is a print of v in the NET_RECEIVE block then things are fine but if there is no print (or just a print of v in the increment block) then the increment never takes effect in ```_actual_v``` as it is not copied back. In other words, if v is changed then NEURON demands that v be mentioned somehow in the NET_RECEIVE block.
```
$ cat vsyn.mod
NEURON {
  POINT_PROCESS VSyn
}

UNITS {
  (mV) = (millivolt)
}

ASSIGNED {
  v (mV)
}

PROCEDURE increment(w(mV)) {
  v = v + w
}

NET_RECEIVE(w(mV)) {
  increment(w)
}
```
The comment in nocmodl nocpout.c must be taken very literally
```
                /* v can be changed in the NET_RECEIVE block since it is
                   called between integrator steps and before a re_init
                   But no need to do so if it is not used.
                */
 ```
in the sense that v must be change **in** the NET_RECEIVE block  and not just in a function called by that block. Ie. in the latter function you can use v but not change it.

**Comment by nrnhines** [comment]
looking into the NEURON nocmodl implementation in nocpout.c in regard to ```netrec_need_v``` I realize that one cannot access v
correctly from a function unless it is also mentioned in the ```NET_RECEIVE``` block. So exactly similar to your warning fix of ```v=0.0;``` I.e.  without a mention of v in the ```NET_RECEIVE``` block, v does not get a copy from ``` v = NODEV(_pnt->node);```

**Comment by pramodk** [comment]
Ok. I will merge then as it is.

**Pull request merged**
